### PR TITLE
Add extension to CentOS packages

### PR DESCRIPTION
**Pull request by popescu-v**
Yum fails to install the packages otherwise.

### CODE REVIEW

**Review by lucaurelien — APPROVED** [review]

**Review by sgouache — COMMENTED** [review]
Looks good, but you could use "install" instead of "localinstall" because it does the same as "install".
In addition since the mpi module loading isn't "magically" working, we should tell the user how to do it e.g. "in order to finalize the installation, elect mpich as the module providing MPI like so" followed by the instructions:
  module unload mpi
  source /etc/profile.d/modules.sh
  mpich_module=$(module avail |& sed -E -e 's/[[:blank:]]+/\n/g' | grep  mpich | tail -n 1)
  module load "$mpich_module"

**Comment by popescu-v** [comment]
> Looks good, but you could use "install" instead of "localinstall" because it does the same as "install". In addition since the mpi module loading isn't "magically" working, we should tell the user how to do it e.g. "in order to finalize the installation, elect mpich as the module providing MPI like so" followed by the instructions: module unload mpi source /etc/profile.d/modules.sh mpich_module=$(module avail |& sed -E -e 's/[[:blank:]]+/\n/g' | grep mpich | tail -n 1) module load "$mpich_module"

Yes, I agree with adding this, but it seems that this needs to be done upon each shell session start. Hence, for practical purposes, I wonder whether one should tell the user add these lines in .bashr or the like (depending on the shell).

**Comment by sgouache** [comment]
Agree, we should lead the user towards a working environment. If it's complicated, explanations need to be further detailed.

**Comment by popescu-v** [comment]
> Agree, we should lead the user towards a working environment. If it's complicated, explanations need to be further detailed.

Do the current explanations (just committed and pushed on this PR) do?

**Pull request merged**
